### ISSUE TITLE
Update modules esling-config to use ^0.1.0

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/eslint-config#9]
### PRs
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/962
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1295
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/221
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2724
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/81
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/109
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/101
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/232
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1257

**Comment by maxime-rainville** [comment]
All done.
